name: "sonar_cloud_scan_github_actions"
on: 
  push:
     branches:
         - "main"

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installing kubectl
        uses: azure/setup-kubectl@v3
        with:
         version: latest  # default is latest stable
        id: install

      - name: version
        run: |
         curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
         chmod +x ./kubectl
         sudo mv ./kubectl /usr/local/bin/kubectl
         kubectl version
      - name: deploying to eks
        run: |
         cd /home/runner/work/SonarQube/SonarQube/k8s-files
         kubectl apply -f .
      