name: "sonar_cloud_scan_github_actions"
on: 
  push:
     branches:
         - "main"

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Deploymemnyt
        run: cd /home/runner/work/DevOps2023-2024-Group3/DevOps2023-2024-Group3/k8s-files 
      - name: deploying to eks
        run: Kubectl apply -f .
      