name: "sonar_cloud_scan_github_actions"
on: 
  push:
     branches:
         - "main"

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installing kubectl
        uses: azure/setup-kubectl@v3
        with:
         version: latest  # default is latest stable
        id: install

      - name: deploying to eks
        run: kubectl apply -f .
      