name: frontend-master-workflow

on: 
  push:
    branches:
      - main
jobs:
  Building_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESSKEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRETEKEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.1.7"

      - name: runnning Terraform Script
        run: |
         ls
         cd terraform/
         ls
         pwd
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        #continue-on-error: true

      - name: Terraform apply
        run: terraform apply -auto-approve
        
        