name: "sonar_cloud_scan_github_actions"
on: 
  push:
     branches:
         - "main"

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploying to eks
        run: Kubectl apply -f .
      