name: "sonar_cloud_scan_github_actions"
on: 
  push:
     branches:
         - "main"

jobs:
  DemoSonarCloudSCan:
    runs-on: self-hosted
    steps:
      - name: checkout code
        run: |
         cd /home/ubuntu/SonarQube/k8s-files
         kubectl create --validate=false
         kubectl apply  -f -k .