name: "sonar_cloud_scan_github_actions"
on: 
  push:
     branches:
         - "main"

jobs:
  DemoSonarCloudSCan:
    runs-on: self-hosted
    steps:
      - name: checkout codes
        run: |
         cd /home/ubuntu/SonarQube/k8s-files
         ls
         kubectl create --validate=false
         kubectl apply  -f  .